{
"dhp1-20":  {"pi": "Yamakavagga ", "en": "Pairs ", "ru": "Парные строфы"},
"dhp100-115":  {"pi": "Appamādavagga ", "en": "Diligence ", "ru": "Строфы о небеспечности"},
"dhp116-128":  {"pi": "Cittavagga ", "en": "The Mind ", "ru": "Строфы об уме"},
"dhp129-145":  {"pi": "Pupphavagga ", "en": "Flowers ", "ru": "Строфы о цветах"},
"dhp146-156":  {"pi": "Bālavagga ", "en": "The Fool ", "ru": "Строфы о глупцах"},
"dhp157-166":  {"pi": "Paṇḍitavagga ", "en": "The Astute ", "ru": "Строфы о мудрецах"},
"dhp167-178":  {"pi": "Arahantavagga ", "en": "The Perfected Ones ", "ru": "Строфы об арахантах"},
"dhp179-196":  {"pi": "Sahassavagga ", "en": "The Thousands ", "ru": "Строфы о тысяче"},
"dhp197-208":  {"pi": "Pāpavagga ", "en": "Wickedness ", "ru": "Строфы о зле"},
"dhp209-220":  {"pi": "Daṇḍavagga ", "en": "The Rod ", "ru": "Строфы о наказании"},
"dhp21-32":  {"pi": "Jarāvagga ", "en": "Old Age ", "ru": "Строфы о старости"},
"dhp221-234":  {"pi": "Attavagga ", "en": "The Self ", "ru": "Строфы о Я"},
"dhp235-255":  {"pi": "Lokavagga ", "en": "The World ", "ru": "Строфы о мире"},
"dhp256-272":  {"pi": "Buddhavagga ", "en": "The Buddhas ", "ru": "Строфы о пробужденном"},
"dhp273-289":  {"pi": "Sukhavagga ", "en": "Happiness ", "ru": "Строфы о счастье"},
"dhp290-305":  {"pi": "Piyavagga ", "en": "The Beloved ", "ru": "Строфы о приятном"},
"dhp306-319":  {"pi": "Kodhavagga ", "en": "Anger ", "ru": "Строфы о гневе"},
"dhp320-333":  {"pi": "Malavagga ", "en": "Stains ", "ru": "Строфы о скверне"},
"dhp33-43":  {"pi": "Dhammaṭṭhavagga ", "en": "The Just ", "ru": "Строфы о соблюдающем дхамму"},
"dhp334-359":  {"pi": "Maggavagga ", "en": "The Path ", "ru": "Строфы о пути"},
"dhp360-382":  {"pi": "Pakiṇṇakavagga ", "en": "Miscellaneous ", "ru": "Строфы о разном"},
"dhp383-423":  {"pi": "Nirayavagga ", "en": "Hell ", "ru": "Строфы о преисподней"},
"dhp44-59":  {"pi": "Nāgavagga ", "en": "Elephants ", "ru": "Строфы о слоне"},
"dhp60-75":  {"pi": "Taṇhāvagga ", "en": "Craving ", "ru": "Строфы о желании"},
"dhp76-89":  {"pi": "Bhikkhuvagga ", "en": "Mendicants ", "ru": "Строфы о бхиккху"},
"dhp90-99":  {"pi": "Brāhmaṇavagga ", "en": "Brahmins ", "ru": "Строфы о брахманах"}
}
