mahākappinavatthu
disaṃgamikādivatthu
codanāvatthubhāṇavāro
vatthuvibhūtakāraṇāti
vatthuddāne
odātavatthavasanakā
soṇakuṭikaṇṇavatthu
pavatthe
pilindavacchavatthu
taruṇapasannamahāmattavatthu
belaṭṭhakaccānavatthu
pāṭaligāmavatthu
sunidhavassakāravatthu
ambapālīvatthu
licchavīvatthu
sīhasenāpativatthu
meṇḍakagahapativatthu
meṇḍakagahapativattha
keṇiyajaṭilavatthu
rojamallavatthu
vuḍḍhapabbajitavatthu
chavatthu
kassapagottabhikkhuvatthu
paccakkhātantimavatthū
saṅghavavatthānaṃ
dīghāvuvatthu
aṭṭhārasavatthukathā
vatthusu
disaṅgamikādivatthu
bhikkhunidūsakavatthu
āpattiyāadassaneukkhittakavatthu









