/* Encodage des caractères en UTF-8 */

function cd() {		
document.write('<div class="bloc">'
+'<div class="haut">'
+'<div class="hautg">'
+'</div>'
+'</div>'
+'<div class="cont">'
+'<div class="h0">choix du style</div>'
+'<ul id="choix">'
+'<li><a id="choixf" href="#">Choisissez</a>'
+'<ul>'
+'<li><a href="#" onclick="setActiveStyleSheet(\'normal\'); return false;" title="(Par défaut)" accesskey="q">&nbsp;&nbsp;Ciel</a></li>'
+'<li><a href="#" onclick="setActiveStyleSheet(\'monastic\'); return false;" title="Fond clair (ancien styles pour les nostalgiques)" accesskey="y">&nbsp;&nbsp;Monacal</a></li>'
+'<li><a href="#" onclick="setActiveStyleSheet(\'chocolate\'); return false;" title="Fond sombre" accesskey="z">&nbsp;&nbsp;Chocolat</a></li>'
+'<li><a href="#" onclick="setActiveStyleSheet(\'minimum\'); return false;" title="Pas de décoration, fond blanc" accesskey="x">&nbsp;&nbsp;Dépouillé</a></li>'
+'</ul>'
+'</li>'
+'</ul><br />'
+'<div class="pttn">'
+'<p>Visitez ce site selon la présentation qui vous convient.</p>'
+'</div>'
+'<div class="pttj">'
+'<noscript><p>Pour changer de style, <a title="Savoir comment procéder lorsque Javascript n\'est pas activé" href="http://dhammadana.org/accessibilite.htm#sj">Javascript</a> doit être activé.</p></noscript>'
+'<p><a title="Explications utiles sur les styles de présentation" href="http://dhammadana.org/accessibilite.htm#ch3">En savoir plus</a></p>'
+'</div>'
+'</div>'
+'</div>'

+'<div class="bloc">'
+'<div class="haut">'
+'<div class="hautg">'
+'</div>'
+'</div>'
+'<div class="cont">'
+'<div class="h0">le bouddhisme</div>'
+'<div class="ptt">'
+'<p>Gardez le bon cap&#8239;!<br /><a href="http://dhammadana.org/extra/bateau.htm">Questions bateau sur le bouddhisme</a></p>'
+'<p>Comment renoncer en pratique<br /><a href="http://dhammadana.org/dhamma/pratique/lachez-tout.htm">Lâchez-tout&#8239;!</a></p>'
+'</div>'
+'</div>'
+'</div>'

+'<div class="bloc">'
+'<div class="haut">'
+'<div class="hautg">'
+'</div>'
+'</div>'
+'<div class="cont">'
+'<div class="h0">roman libre</div>'
+'<div class="ptt">'
+'<p>Avez-vous déjà lu le dernier roman de isi&nbsp;Dhamma&#8239;?<br /><a href="http://neil.dhammadana.org" title="Le dernier roman de isi Dhamma"><img src="../../im/neil-130x130.png" /><br /><strong>Un enfant sur la&nbsp;Lune</strong></a></p>'
+'</div>'
+'</div>'
+'</div>'

+'<div class="bloc">'
+'<div class="haut">'
+'<div class="hautg">'
+'</div>'
+'</div>'
+'<div class="cont">'
+'<div class="h0">j\'<img src="http://dhammadana.org/im/coeur.png" alt="aime" /> dhammadāna</div>'
+'<div class="ptt">'
+'<p><a href="http://dhammadana.org/dana.htm" title="Comment aider dhammadāna&#8239;?">Comment aider&#8239;?</a></p>'
+'</div>'
+'</div>'
+'</div>'

+'<div class="bloc">'
+'<div class="haut">'
+'<div class="hautg">'
+'</div>'
+'</div>'
+'<div class="cont">'
+'<div class="ptt">'
+'<p><span class="it">Infos utiles</span></p>'
+'<p><a href="http://dhammadana.org/aide.htm" title="Page d\'aide à l\'utilisation de ce site">Aide</a></p>'
+'<p><a href="http://dhammadana.org/accessibilite.htm" title="Politique d\'accessibilité">Accessibilité</a></p>'
+'<p><a href="http://dhammadana.org/contact.htm" title="pour contacter l\'administrateur">Envoyez un mail</a></p>'
+'<a rel="license" title="Licence Creative Commons. Paternité - Pas d\'Utilisation Commerciale - Pas de Modification" href="http://dhammadana.org/droits.htm"><img class="miniban" alt="Creative Commons" src="http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png" /></a>'
+'<a title="Pour votre tranquillité, ce site refuse toute publicité." href= "http://blogantipub.wordpress.com/charte-des-sites-sans-pub/"><img class="miniban" alt="" src= "http://blogantipub.files.wordpress.com/2006/09/sitesanspub.png" /></a>'
+'<a title="Un navigateur plus léger, plus rapide, plus respectueux." href= "http://www.google.com/chrome?hl=fr"><img class="miniban" alt="" src= "http://dhammadana.org/im/googlechrome.png" /></a>'
+'<a title="Une disposition du clavier tellement plus reposante et plus logique..." href= "http://bepo.fr/wiki/Presentation"><img class="miniban" alt="" src= "http://dhammadana.org/im/bepo.png" /></a>'
+'</div>'
+'</div>'
+'</div>');
}
