/* Encodage des caractères en UTF-8 */

function cg() {		
document.write('<div class="bloc">'
+'<div class="haut">'
+'<div class="hautg">'
+'</div>'
+'</div>'
+'<div class="cont">'
+'<div class="h0">rechercher sur dhammadana.org</div>'
+'<div class="ptt">'

+'<script type="text/javascript" src="http://www.google.com/jsapi"></script>'
+'<script type="text/javascript">'
+'  google.load(\'search\', \'1\');'
+'  google.setOnLoadCallback(function() {'
+'    google.search.CustomSearchControl.attachAutoCompletion('
+'      \'004764843378458177922:pxuxlq0zwoo\','
+'      document.getElementById(\'q\'),'
+'      \'cse-search-box\');'
+'  });'
+'</script>'
+'<form action="http://dhammadana.org/recherche.htm" id="cse-search-box">'
+'  <div>'
+'    <input type="hidden" name="cx" value="004764843378458177922:pxuxlq0zwoo" />'
+'    <input type="hidden" name="cof" value="FORID:9" />'
+'    <input type="hidden" name="ie" value="UTF-8" />'
+'    <input type="text" name="q" id="q" autocomplete="on" size="16" />'
+'    <input type="submit" name="sa" value="ok" />'
+'  </div>'
+'</form>'
+'<script type="text/javascript" src="http://www.google.com/cse/brand?form=cse-search-box&lang=fr"></script>'
+'</div>'
+'</div>'
+'</div>'

+'<div class="bloc">'
+'<div class="haut">'
+'<div class="hautg">'
+'</div>'
+'</div>'
+'<div class="cont">'
+'<div class="h0">astuces</div>'
+'<div class="ptt">'
+'<ul class="lfl2">'
+'<li>Survolez <span class="dur" title="...et vous obtiendrez une brève explication">les mots soulignés de pointillés</span>...</li>'
+'<li>Pour une vue d\'ensemble, pensez au <a href="http://dhammadana.org/plan.htm">plan&nbsp;du&nbsp;site</a>.</li>'
+'</ul>'
+'</div>'
+'</div>'
+'</div>'

+'<div class="bloc">'
+'<div class="haut">'
+'<div class="hautg">'
+'</div>'
+'</div>'
+'<div class="cont">'
+'<div class="h0">politique de navigation tranquille</div>'
+'<div class="ptt">'
+'<p>Par respect pour ses visiteurs, ce site ne comporte ni publicité, ni animation, ni ouverture de fenêtre.</p>'
+'</div>'
+'</div>'
+'</div>'

+'<div class="bloc">'
+'<div class="haut">'
+'<div class="hautg">'
+'</div>'
+'</div>'
+'<div class="cont">'
+'<div class="h0">forums</div>'
+'<div class="ptt">'
/*
+'<p>Nous avons tous une part de sagesse que les autres n\'ont pas. Partageons notre trésor intérieur&#8239;!</p>'
+'<p>Rejoignez le <strong>Forum Mettā</strong> (bouddhisme originel)&#8239;:</p>'
+'<a href="http://forumetta.free.fr/" title="Vers le forum Mettā"><img class="ima" style="width:80px; height:89px; margin-left: 8px;" src="http://dhammadana.org/im/metta.gif" alt="Logo du forum Mettā" /></a>'
+'<p>et le <strong>Forum Nangpa</strong> (bouddhisme en général)&#8239;:</p>'
+'<a href="http://nangpa2.free.fr/phpBB3//" title="Vers le forum Nangpa"><img class="ima" style="width:48px; height:54px; margin-left: 8px;" src="http://dhammadana.org/im/nangpa.jpg" alt="Logo du forum Nangpa" /></a>'
*/
+'<p>Nous avons tous une part de sagesse que les autres n\'ont pas. Partageons notre trésor intérieur&#8239;!</p>'
+'<p>Rejoignez le groupe <strong>le Bouddhisme, un Art de vivre</strong> (pur Dhamma)&nbsp;:</p>'
+'<a href="https://www.facebook.com/groups/216262018400976/" title="Vers le groupe \'le Bouddhisme, un Art de vivre\'"><img class="ima" style="width:100px; height:130px; margin-left: 8px;" src="http://dhammadana.org/im/gouranga.jpg" alt="Logo du groupe le bouddhisme un art de vivre" /></a>'
+'<p>le <strong>Forum Mettā</strong> (bouddhisme originel)&#8239;:</p>'
+'<a href="http://forumetta.free.fr/" title="Vers le forum Mettā"><img class="ima" style="width:80px; height:89px; margin-left: 8px;" src="http://dhammadana.org/im/metta.gif" alt="Logo du forum Mettā" /></a>'
+'<p>et le <strong>Forum Nangpa</strong> (bouddhisme en général)&#8239;:</p>'
+'<a href="http://nangpa2.free.fr/phpBB3//" title="Vers le forum Nangpa"><img class="ima" style="width:48px; height:54px; margin-left: 8px;" src="http://dhammadana.org/im/nangpa.jpg" alt="Logo du forum Nangpa" /></a>'

+'</div>'
+'</div>'
+'</div>');
}
