/* Encodage des caractères en UTF-8 */

sfHover = function() {

	var sfEls = document.getElementById("md").getElementsByTagName("LI");

	for (var i=0; i<sfEls.length; i++) {

	sfEls[i].onmouseover=function() {

	this.className+=" sfhover";

	}

	sfEls[i].onmouseout=function() {

	this.className=this.className.replace(new RegExp(" sfhover\\b"), "");

	}

	}

	}
if (window.attachEvent) window.attachEvent("onload", sfHover);

sfHover = function() {

	var sfEls = document.getElementById("choix").getElementsByTagName("LI");

	for (var i=0; i<sfEls.length; i++) {

	sfEls[i].onmouseover=function() {

	this.className+=" sfhover";

	}

	sfEls[i].onmouseout=function() {

	this.className=this.className.replace(new RegExp(" sfhover\\b"), "");

	}

	}

	}
if (window.attachEvent) window.attachEvent("onload", sfHover);

function gm() {		
document.write('<ul id="md">'
+'<li><a href="../../extra.htm" class="papa">Extra</a>'
+'	<ul>'
+'	<li><a href="../../extra/infos.htm" class="papa" accesskey="2">Infos</a>'
+'		<ul>'
+'		<li><a href="../../extra/infos/quelle-meditation.htm">Quelle méditation choisir&#8239;?</a></li>'
+'		<li><a href="../../extra/infos/ds-a7d.htm">De Dhamma Sāmi à A7 Dhamma</a></li>'
+'		<li><a href="../../extra/infos/coulisses.htm">Les coulisses de dhammadana.org</a></li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="../../extra/bateau.htm" accesskey="5">Questions "bateau" sur le bouddhisme</a></li>'
+'	<li><a href="../../extra/bouddhisme.htm">Le bouddhisme en quelques lignes...</a></li>'
+'	<li><a href="../../extra/faq.htm">Questions fréquentes</a></li>'
+'	<li><a href="../../extra/test.htm" class="papa">Test</a>'
+'		<ul>'
+'		<li><a href="../../extra/test/vie_monacale.htm">Vie monacale&#8239;?</a></li>'
+'		<li><a href="../../extra/test/partie1.htm">Quelle renaissance&#8239;?</a></li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="../../extra/photos.htm" class="papa">Photographies</a>'
+'		<ul>'
+'		<li><a href="../../extra/photos/2010_paauk.htm">Monastère Pa&nbsp;Auk (2010)</a></li>'
+'		<li><a href="../../extra/photos/2005_myanmar.htm">Myanmar (2005)</a></li>'
+'		<li><a href="../../extra/photos/2003_myanmar.htm">Monastères (2003)</a></li>'
+'		<li><a href="../../extra/photos/2002_myanmar.htm">Myanmar (2002)</a></li>'
+'		<li><a href="../../extra/photos/2002_cambodge.htm">Cambodge (2002)</a></li>'
+'		<li><a href="../../extra/photos/2002_laos.htm">Laos (2002)</a></li>'
+'		<li><a href="../../extra/photos/1999_myanmar.htm">Myanmar (1999)</a></li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="../../extra/interviews.htm" class="papa">Interviews</a>'
+'		<ul>'
+'		<li><a href="../../extra/interviews/novice-kn.htm">Novice Kavindā Nanda</a></li>'
+'		<li><a href="../../extra/interviews/moine-sv.htm">Moine Sīla Vanta</a></li>'
+'		<li><a href="../../extra/interviews/nonne-nm.htm">Nonne Nanda Mālā</a></li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="../../extra/audio_video.htm">Enseignements audio et vidéo</a></li>'
+'	<li><a href="../../extra/fonds.htm">Fonds d&#39;écran</a></li>'
+'	</ul>'
+' </li>'
+' <li><a href="../../bouddha.htm" class="papa">Bouddha</a>'
+'	<ul>'
+'	<li><a href="#" class="papa sm" title="Choisissez --&gt;">Le boddhisatta</a>'
+'		<ul>'
+'		<li><a href="../../bouddha/sumedha.htm">L&#39;ermite Sumedha</a></li>'
+'		<li><a href="../../bouddha/10_parami.htm">Les 10 pāramī du boddhisatta</a></li>'
+'		<li><a href="../../bouddha/vessantara.htm">Le roi Vessantarā</a></li>'
+'		<li><a href="../../bouddha/avant_derniere_vie.htm">L&#39;avant-dernière vie du futur Bouddha</a></li>'
+'		<li><a href="../../bouddha/32_caracteristiques.htm">Les 32 caractéristiques d&#39;un bouddha</a></li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="#" class="papa sm" title="Choisissez --&gt;">Le prince siddhattha</a>'
+'		<ul>'
+'		<li><a href="../../bouddha/naissance.htm">La naissance du futur Bouddha</a></li>'
+'		<li><a href="../../bouddha/enfance.htm">L&#39;enfance du prince Siddhattha</a></li>'
+'		<li><a href="../../bouddha/4_grands_signes.htm">Les 4 grands signes</a></li>'
+'		<li><a href="../../bouddha/depart_foret.htm">Le départ pour la forêt</a></li>'
+'		<li><a href="../../bouddha/austerites.htm">Les 6 ans d&#39;austérités</a></li>'
+'		<li><a href="../../bouddha/voie_moyenne.htm">La voie moyenne</a></li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="#" class="papa sm" title="Choisissez --&gt;">L&#39;éveil</a>'
+'		<ul>'
+'		<li><a href="../../bouddha/eveil.htm">L&#39;éveil de Bouddha</a></li>'
+'		<li><a href="../../bouddha/49_jours.htm">Les 49 jours après l&#39;éveil</a></li>'
+'		<li><a href="../../bouddha/sahampati.htm">La sollicitation du brahmā Sahampati</a></li>'
+'		<li><a href="../../bouddha/premier_sermon.htm">Les premiers enseignements de Bouddha</a></li>'
+'		<li><a href="../../bouddha/yasa.htm">L&#39;intégration du riche Yasa dans le sangha</a></li>'
+'		<li><a href="../../bouddha/propagation.htm">La propagation du dhamma</a></li>'
+'		<li><a href="../../bouddha/3_kassapa1.htm">À propos des 3 frères Kassapa</a></li>'
+'		<li><a href="../../bouddha/3_kassapa2.htm">L&#39;entrée des 3 frères Kassapa dans le sangha</a></li>'
+'		<li><a href="../../bouddha/rajagaha.htm">L&#39;arrivée de Bouddha à Rājāgaha</a></li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="#" class="papa sm" title="Choisissez --&gt;">Les disciples moines</a>'
+'		<ul>'
+'		<li><a href="../../bouddha/sariputtara_moggalana.htm">Vénérables Sāriputtarā et Mahā Moggalāna</a></li>'
+'		<li><a href="../../bouddha/kondanna.htm">Vénérable Konḍañña</a></li>'
+'		<li><a href="../../bouddha/bhaddavaggi.htm">Les 30 moines Bhaddavaggī</a></li>'
+'		<li><a href="../../bouddha/kapilavatthu.htm">Le retour à Kapilavatthu</a></li>'
+'		<li><a href="../../bouddha/nanda.htm">L&#39;entrée du prince Nanda dans le sangha</a></li>'
+'		<li><a href="../../bouddha/anuruddha.htm">Vénérable Anuruddhā</a></li>'
+'		<li><a href="../../bouddha/ananda.htm">Vénérable Ānandā</a></li>'
+'		<li><a href="../../bouddha/maha_kassapa.htm">Le passé du Vénérable Mahā Kassapa</a></li>'
+'		<li><a href="../../bouddha/rahula_ratthapala.htm">Vénérables Rāhulā et Ratthapāla</a></li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="#" class="papa sm" title="Choisissez --&gt;">Les disciples moniales</a>'
+'		<ul>'
+'		<li><a href="../../bouddha/gotami1.htm">Le passé de Mahāpajāpati Gotamī</a></li>'
+'		<li><a href="../../bouddha/gotami2.htm">À propos de Mahāpajāpati Gotamī</a></li>'
+'		<li><a href="../../bouddha/yasodhara.htm">À propos de Yasodharā</a></li>'
+'		<li><a href="../../bouddha/khema.htm">La reine Khemā</a></li>'
+'		<li><a href="../../bouddha/ambapalika.htm">La courtisane Ambapālikā</a></li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="#" class="papa sm" title="Choisissez --&gt;">Les disciples laïcs</a>'
+'		<ul>'
+'		<li><a href="../../bouddha/sudoddhana.htm">Le parinibbāna du roi Sudoddhana</a></li>'
+'		<li><a href="../../bouddha/jivaka.htm">Le docteur Jīvaka</a></li>'
+'		<li><a href="../../bouddha/jetavana.htm">Le dāyaka Anāthapinḍika</a></li>'
+'		<li><a href="../../bouddha/ajatasatu.htm">La vénération du roi Ajātasatu pour Bouddha</a></li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="#" class="papa sm" title="Choisissez --&gt;">Principaux sermons</a>'
+'		<ul>'
+'		<li><a href="../../bouddha/pouvoirs.htm">La démonstration des pouvoirs psychiques</a></li>'
+'		<li><a href="../../bouddha/abhidhamma.htm">L&#39;enseignement de l&#39;abhidhamma</a></li>'
+'		<li><a href="../../bouddha/baka.htm">Le brahmā Baka</a></li>'
+'		<li><a href="../../bouddha/castes.htm">Bouddha et les castes</a></li>'
+'		<li><a href="../../bouddha/kalamas.htm">Le sermon aux Kālāmas</a></li>'
+'		<li><a href="../../bouddha/culamalukyaputta.htm">Le sermon au Vénérable Cūlamālukyaputta</a></li>'
+'		<li><a href="../../bouddha/religieux.htm">Bouddha et les maîtres religeux</a></li>'
+'		<li><a href="../../bouddha/labourage.htm">Le labourage de Bouddha</a></li>'
+'		<li><a href="../../bouddha/autres_sermons.htm">Autres sermons</a></li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="#" class="papa sm" title="Choisissez --&gt;">Les principaux conflits</a>'
+'		<ul>'
+'		<li><a href="../../bouddha/devadata.htm">La division du sangha par Devadatta</a></span></li>'
+'		<li><a href="../../bouddha/rohini.htm">Le conflit de la rivière Rohinī</a></li>'
+'		<li><a href="../../bouddha/magandiya.htm">La haine de Māganḍiya envers Bouddha</a></li>'
+'		<li><a href="../../bouddha/sundari.htm">La femme ascète Sundarī</a></li>'
+'		<li><a href="../../bouddha/cinkhamana.htm">L&#39;accusation de Ciñkhamāna contre Bouddha</a></li>'
+'		<li><a href="../../bouddha/dispute.htm">La dispute des moines</a></li>'
+'		<li><a href="../../bouddha/mara.htm">L&#39;oppression de Māra au moine Mahā Moggalāna</a></li>'
+'		<li><a href="../../bouddha/angulimala.htm">Angulimāla, le coupeur de doigts</a></li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="#" class="papa sm" title="Choisissez --&gt;">parinibbāna, etc.</a>'
+''
+'		<ul>'
+'		<li><a href="../../bouddha/vassa.htm">Les &quot;vassa&quot; de Bouddha</a></li>'
+'		<li><a href="../../bouddha/dernier_vassa.htm">Le dernier vassa de Bouddha</a></li>'
+'		<li><a href="../../bouddha/parinibbana_sariputtara.htm">Le parinibbāna du Vénérable Sāriputtarā</a></li>'
+'		<li><a href="../../bouddha/parinibbana_moggalana.htm">Le parinibbāna du Vénérable Mahā Moggalāna</a></li>'
+'		<li><a href="../../bouddha/parinibbana_bouddha.htm">Le parinibbāna de Bouddha</a></li>'
+'		<li><a href="../../bouddha/concile.htm">Le premier concile</a></li>'
+'		</ul>'
+'	</li>'
+'	</ul>'
+' </li>'
+' <li><a href="../../dhamma.htm" class="papa">Dhamma</a>'
+'	<ul>'
+'	<li><a href="../../dhamma/kamma.htm" class="papa">Le kamma</a>'
+'		<ul>'
+'		<li><a href="../../dhamma/kamma/dettes.htm">Qui paye ses dettes s&#39;enrichit</a>'
+'		</li>'
+'		<li><a href="../../dhamma/kamma/voir-ses-vies.htm">Les vies d&#39;un moine</a> <span class="gris">'
+'		</li>'
+'		<li><a href="../../dhamma/kamma/samsara.htm">Le saṃsāra</a>'
+'		</li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="../../dhamma/pratique.htm" class="papa">Pratique bouddhiste</a>'
+'		<ul>'
+'		<li><a href="../../dhamma/pratique/feu.htm">Il y a le feu&#8239;!</a></li>'
+'		<li><a href="../../dhamma/pratique/laique.htm">La pratique laïque</a></li>'
+'		<li><a href="../../dhamma/pratique/8_preceptes.htm">Les 8 préceptes</a></li>'
+'		<li><a href="../../dhamma/pratique/liberation.htm">La voie libératrice</a></li>'
+'		<li><a href="../../dhamma/pratique/lachez-tout.htm">Lâchez tout&#8239;!</a></li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="../../dhamma/en-3-mots.htm">En 3 mots...</a></li>'
+'	<li><a href="../../dhamma/paticca_samuppada.htm">paṭicca samuppāda</a></li>'
+'	<li><a href="../../dhamma/5_agregats.htm">Les 5 agrégats</a></li>'
+'	<li><a href="../../dhamma/3_caracteristiques.htm" class="papa">3 caractéristiques</a>'
+'		<ul>'
+'		<li><a href="../../dhamma/3_caracteristiques/anicca.htm">anicca</a></li>'
+'		<li><a href="../../dhamma/3_caracteristiques/dukkha.htm">dukkha</a></li>'
+'		<li><a href="../../dhamma/3_caracteristiques/anatta.htm">anatta</a></li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="../../dhamma/nibbana.htm">nibbāna</a></li>'
+'	<li><a href="../../dhamma/jhana_nibbana.htm">jhāna et nibbāna</a></li>'
+'	<li><a href="../../dhamma/6_mondes.htm">Les 6 mondes</a></li>'
+'	<li><a href="../../dhamma/4_paramattha.htm">Les 4 paramattha</a></li>'
+'	</ul>'
+' </li>'
+' <li><a href="../../sangha.htm" class="papa">Sangha</a>'
+'	<ul>'
+'	<li><a href="../../sangha/vinaya.htm" class="papa">Le vinaya</a>'
+'		<ul>'
+'		<li><a href="../../sangha/vinaya/patimokkha.htm">Le pātimokkha</a></li>'
+'		<li><a href="../../sangha/vinaya/227.htm">Les 227 règles</a></li>'
+'		<li><a href="../../sangha/vinaya/hors_patimokkha.htm">Hors pātimokkha</a></li>'
+'		<li><a href="../../sangha/vinaya/autres_points.htm">Autres points</a></li>'
+'		<li><a href="../../sangha/vinaya/kathina.htm">Le kathina</a></li>'
+'		<li><a href="../../sangha/vinaya/novices.htm">Les novices</a></li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="../../sangha/dhutanga.htm" class="papa">Les 13 dhutaṅga</a>'
+'		<ul>'
+'<li><a href="../../sangha/dhutanga/01.pamsukula.htm">paṃsukūla</a></li>'
+'<li><a href="../../sangha/dhutanga/02.tecivarika.htm">tecīvarika</a></li>'
+'<li><a href="../../sangha/dhutanga/03.pindapata.htm">piṇḍapāta</a></li>'
+'<li><a href="../../sangha/dhutanga/04.sapadanacarika.htm">sapadānacārika</a></li>'
+'<li><a href="../../sangha/dhutanga/05.ekasanika.htm">ekāsanika</a></li>'
+'<li><a href="../../sangha/dhutanga/06.pattapindika.htm">pattapiṇḍika</a></li>'
+'<li><a href="../../sangha/dhutanga/07.khalupacchabhattika.htm">khalupacchābhattika</a></li>'
+'<li><a href="../../sangha/dhutanga/08.arannika.htm">āraññika</a></li>'
+'<li><a href="../../sangha/dhutanga/09.rukkhamula.htm">rukkhamūla</a></li>'
+'<li><a href="../../sangha/dhutanga/10.abbhokasika.htm">abbhokāsika</a></li>'
+'<li><a href="../../sangha/dhutanga/11.susanika.htm">susānika</a></li>'
+'<li><a href="../../sangha/dhutanga/12.yathasantatika.htm">yathāsantatika</a></li>'
+'<li><a href="../../sangha/dhutanga/13.nesajjika.htm">nesajjika</a></li>'
+'		</ul>'
+'	</li>'
+'	<li><a href="../../sangha/moines.htm" class="papa">Les moines</a>'
+'		<ul>'
+'		<li><a href="../../sangha/moines/devenir.htm">Devenir bhikkhu</a></li>'
+'		<li><a href="../../sangha/moines/affaires.htm">Affaires du bhikkhu</a></li>'
+'		<li><a href="../../sangha/moines/a_propos.htm">Au sujet des moines</a></li>'
+'		</ul>'
+'	</li>'
+' 	<li><a href="../../sangha/vie_monastique.htm">Vie monastique</a></li>'
+'	<li><a href="../../sangha/monasteres.htm">Les monastères</a></li>'
+'	<li><a href="../../sangha/conciles.htm">Les 6 conciles</a></li>'
+'	</ul>'
+' </li>'
+'<li><a href="../../sutta.htm" class="papa">Souttas</a>'

+'		<ul>'
+'		<li><a href="../../sutta/mn.htm">Majjhima Nikāya</a></li>'
+'		<li><a href="../../sutta/canon-pali.htm">Canon Pali</a></li>'
+'		<li><a href="../../sutta/7-etapes.htm">Dhamma en 7 étapes</a></li>'
+'		</ul>'

+'</li>'

+'<li><a href="../../samatha.htm" class="papa">Samatha</a>'

+'		<ul>'
+'		<li><a href="../../samatha/kammathana.htm" class="papa">Les 40 objets</a>'
+'			<ul>'
+'			<li><a href="../../samatha/kammathana/4-protections.htm">Les 4 protections</a></li>'
+'			<li><a href="../../samatha/kammathana/anussati.htm">Anussati</a></li>'
+'			<li><a href="../../samatha/kammathana/32-parties-du-corps.htm">32 parties du corps</a></li>'
+'			<li><a href="../../samatha/kammathana/asubha.htm">Asubha</a></li>'
+'			</ul>'
+'		</li>'
+'		<li><a href="../../samatha/anapana.htm" class="papa"><span xml:lang="pi">Ānāpāna sati</span></a>'
+'			<ul>'
+'			<li><a href="../../samatha/anapana/belle-respiration.htm">La belle respiration</a></li>'
+'			<li><a href="../../samatha/anapana/lettre-nonne.htm">Lettre d&#39;une nonne</a></li>'
+'			</ul>'
+'		</li>'
+'		<li><a href="../../samatha/nivarana.htm">Les 5 entraves</a>'
+'		</li>'
+'		<li><a href="../../samatha/nimitta.htm">Le nimitta</a>'
+'		</li>'
+'		</ul>'

+'</li>'

+' <li><a href="../../vipassana.htm" class="papa">Vipassanā</a>'
+'	<ul>'
+'	<li><a href="../../vipassana/qu_est_ce.htm">Qu&#39;est-ce&#8239;?</a></li>'
+'	<li><a href="../../vipassana/instructions.htm">Instructions de base</a></li>'
+'	<li><a href="../../vipassana/enseignements.htm">Enseignements</a></li>'
+'	<li><a href="../../vipassana/aaz.htm">De A à Z</a></li>'
+'	<li><a href="../../vipassana/comment_noter.htm">Comment noter&#8239;?</a></li>'
+'	<li><a href="../../vipassana/ou_pratiquer.htm">Où pratiquer&#8239;?</a></li>'
+'	<li><a href="../../vipassana/voie_moderee.htm">La voie modérée</a></li>'
+'	<li><a href="../../vipassana/conseils.htm">Conseils</a></li>'
+'	</ul>'
+'</li>'
+'</ul>');
}